[project]
name = "yamlicious"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fable-library>=5.0.0a21",
    "pytest>=9.0.2",
]
